id: A0A82DC0D
title: Bodhicaryāvatāra Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:01:47.741890
  last_modified_at: 2022-03-01 01:01:47.741902
