id: A0A82DC0D
title: Prayer to the Lineage of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:01:47.746024
  last_modified_at: 2022-03-01 01:01:47.746032
