id: A0A82DC0D
title: 'The Purifier of Ethical Discipline: An Aspirational Praise to Vajradhara Kunga
  Zangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:01:47.749687
  last_modified_at: 2022-03-01 01:01:47.749692
